# Generated by Django 4.2.5 on 2023-09-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_platform', '0003_alter_venue_latitude_alter_venue_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
